### ISSUE TITLE
Chocolate has unlisted dependency on Forge 34.1.33, resulting in unexpected crashes with anything lower

### ISSUE THREAD

**Issue by BedrockLegends** [alcatrazEscapee/Chocolate#2] opened 2020-10-30 04:43 UTC
[crash-2020-10-29_22.19.21-client.txt](https://github.com/alcatrazEscapee/Chocolate/files/5463030/crash-2020-10-29_22.19.21-client.txt)

**Comment by alcatrazEscapee** [comment] 2020-10-30 13:04
I'm not sure how you arrived at that conclusion. The crash log is saying that an `undergarden:stoneborn` entity is somehow causing an explosion, which is crashing at Server Utils `com.github.elrol.ElrolsUtilities.events.BlockEventHandler`.

Unfortunately, I cannot find any reference to this class in Server Utilities source code to confirm my suspicions. I highly recommend you report the issue to either Server Utilities, or The Undergarden as they seem to be involved. I have asked the developers of the former about this to see if they have anything to add.

Any more info would be appreciated as I'm pretty sure this is not Chocolate's bug.

**Comment by alcatrazEscapee** [comment] 2020-10-30 13:53
![msg](https://user-images.githubusercontent.com/35673674/97713002-9bb96580-1a95-11eb-9cf7-0ad00f789b2c.JPG)

After asking the author, this sounds like it's probably an issue with Server Utilities and/or The Undergarden and should be reported as such. I'm closing this as I see nothing that Chocolate is doing to cause this, nor anything I would be able to do to fix this.

**Comment by Elrol** [comment] 2020-10-30 15:17
The issue isnt my mod. I am just adding a few checks to make sure that mods that dont implement things properly dont crash the server. 

One of my more active testers has over 200 mods and it was working fine. He reported the issues after adding your mod. So something must not be playing well together. Either way i will attempt to fix the issues introduced by mod conflicts.

**Comment by alcatrazEscapee** [comment] 2020-10-30 15:36
If that is the case, I'd like to see anything in there that would point to it being Chocolate's error. I fix two biome serialization bugs in vanilla. Both of which, if they throw exceptions (which they have been written to do in error states), will clearly identify that Chocolate has thrown them. [i.e. here](https://github.com/alcatrazEscapee/Chocolate/blob/0938f7c6d25d528ab264cfda8b10896903bfdd2d/src/main/java/com/alcatrazescapee/chocolate/mixin/world/biome/BiomeContainerMixin.java#L52).

However, looking at that crashlog

- There's nothing to do with biomes, or chunk serialization
- Chocolate isn't even in the stack trace, and moreover, 
- Chocolate isn't even in the included mod list. There's no evidence whatsoever that chocolate was even included in the server at time of crash, let alone caused it, let alone any indication of how to fix it.

Is there an actual issue here and the wrong crash log was uploaded perhaps?

**Comment by BedrockLegends** [comment] 2020-10-31 00:21
[crash-2020-10-30_18.55.53-client.txt](https://github.com/alcatrazEscapee/Chocolate/files/5468226/crash-2020-10-30_18.55.53-client.txt)

[latest.log](https://github.com/alcatrazEscapee/Chocolate/files/5468234/latest.log)


[debug.log](https://github.com/alcatrazEscapee/Chocolate/files/5468232/debug.log)

As soon as I put this Mod into my pack, it crashes even on the new update, If I dont add this mod at all then nothing crashes. This is all on your mod as it only happens after adding it

**Comment by alcatrazEscapee** [comment] 2020-10-31 00:52
That debug log is very interesting. A couple things that stand out:

```
[30Oct2020 19:18:22.881] [main/WARN] [mixin/]: Error loading class: net/minecraftforge/registries/ForgeRegistryEntry$UncheckedRegistryEntry (java.lang.ClassNotFoundException: null)
```

This is due to the fact Chocolate was built against Forge 34.1.33, which introduced `UncheckedRegistryEntry`. However I have made a mistake and not set the required Forge version in the `mods.toml` to this version. As per the log, this is currently using Forge 34.1.25. So there is issue no. 1.

```
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry
	at net.minecraft.item.ItemStack.lambda$static$3(ItemStack.java:77) ~[?:?] {re:mixin,re:classloading,xf:fml:apotheosis:apothitemusehook,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
```

This is also *highly* concerning. This would seem to indicate that a transformer has ran into a conflict, although nothing here points to Chocolate being the cause. (as this is transforming `ItemStack`, something Chocolate does not go anywhere near).

So: update your forge version to 34.1.33. I will make chocolate require it as of the next build. If this still crashes, then post the debug.log again and we can investigate, capiche?

**Comment by BedrockLegends** [comment] 2020-10-31 00:57
@alcatrazEscapee I cant update my forge version as Mods are still crashing in my pack cause of the new forge breaking changes

**Comment by alcatrazEscapee** [comment] 2020-10-31 01:35
*grumbles incoherently*

Well then I'll see what I can do.

**Comment by BedrockLegends** [comment] 2020-10-31 02:01
Well if this helps so far out of 70 mods + yours Immersive Engineering crashes

**Comment by alcatrazEscapee** [comment] 2020-10-31 02:30
Okay, the process of backporting through Forge versions begins...

First step: Remove the unnecessary reference to `UncheckedRegistryEntry`. It now compiles against 34.0.0. Fantastic! Except now it crashes on anything lower than 34.1.31, because guess what - this mod relies quite a lot on a fix added in that version (one that I had made to Forge).

So there may be more bodging required...

*Although in the meantime, identifying which mods are broken on newer versions of Forge and reporting it to them so they can update will always be helpful* :)

**Closed as completed** 2020-10-31 15:20 UTC
Labels: Version: 1.16.x Forge, Need Information
